
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbejegsgohrnxjsxzycp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZWplZ3Nnb2hybnhqc3h6eWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTExNDYsImV4cCI6MjA2MjA2NzE0Nn0.vgfKMFKeX2gTH0dnLzdnm3_Fxq3zs0BmhJhs6R0UwtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Log the connection status to help with debugging
supabase.auth.onAuthStateChange((event, session) => {
  console.log("Supabase auth state changed:", event);
});

// Add a simple function to test the connection
export const testSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('appointments').select('count').limit(1);
    if (error) {
      console.error("Supabase connection test failed:", error);
      return false;
    }
    console.log("Supabase connection successful:", data);
    return true;
  } catch (error) {
    console.error("Unexpected error testing Supabase connection:", error);
    return false;
  }
};
