// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbejegsgohrnxjsxzycp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZWplZ3Nnb2hybnhqc3h6eWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTExNDYsImV4cCI6MjA2MjA2NzE0Nn0.vgfKMFKeX2gTH0dnLzdnm3_Fxq3zs0BmhJhs6R0UwtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);